Configurable headers+QoL
DeloitteAU/ddmock-ios pull request #4
Opened 2021-06-17 04:14 UTC by will-rigney

In progress RF + new features added to DDMock.

Still todo: usability & quality updates, documentation + tests.

2021-06-17 04:28 UTC, tplester commented on DDMockiOS.podspec
> +  spec.version          = '2.0'
0.1 to 2.0 is a pretty big jump

2021-06-17 04:45 UTC, tplester requested changes
The url for Cocoapod needs to be reverted, otherwise looks ok.

2021-06-17 04:45 UTC, tplester commented on DDMockiOS.podspec
> +  spec.source           = { :git => "https://github.com/will-rigney/ddmock-ios.git", :tag => 'v' + spec.version.to_s }
This needs to be set back to the right url

2025-05-23 04:30 UTC, christopher-hopper commented
⚠️ This repository is no longer maintained and has been archived.

Thank you for your contributions. Closing this pull request.

2025-05-23 04:30 UTC, closed without merging